### ISSUE TITLE
有些疑问

### ISSUE THREAD

**Issue by bjyh345** [ceynri/szu-network-connecter#4]
首先，师兄好强！
我想问下如果被校方发现，算不算违规操作？
还有，有线连接的话，打开Drcom就自动登录了呀，那和打开Chrome所需要的步骤不是一样的吗？

**Comment by ceynri** [comment]
> 我想问下如果被校方发现，算不算违规操作？

不算违规操作哈，并没有做什么恶意破解，只是模拟了一下请求而已

> 打开Drcom就自动登录了呀，那和打开Chrome所需要的步骤不是一样的吗？

做成chrome插件的形式，一方面是我想试试水，另一方面，drcom客户端需要挂在后台，而插件或者网页登录是不需要的；而且客户端需要选择“教学区/宿舍区”再点确定，如果用户一般上网是为了上网页的话，启动chrome浏览器是顺带的事；再者就是ui古老，windows高分屏下模糊，且个人感觉容易掉线（不过，我已两年不用drcom客户端，不知道现在掉线情况如何）

**Comment by bjyh345** [comment]
好的！drcom确实是要多点一下确定，不过稳定性挺好，只是有时候连接上去比较慢。一直很感兴趣也很喜欢这种把所学的知识用于方便生活的想法，没想到偶然在github上看到师兄（or师姐？）这个插件，真不错！向大佬学习👍

**Comment by ceynri** [comment]
多多思考勤于动手，你也可以做到哈~加油
