### ISSUE TITLE
关于localStorage存储位置

### ISSUE THREAD

**Issue by miRemid** [ceynri/szu-network-connecter#7]
本人在Edge(93.0.961.44)中使用该插件，能正常工作，但我不知该去哪寻找localStorage中存储的密码信息

想问下扩展中localStorage存储的位置在哪里

另外，能否增加清除账号或退出账号功能

**Comment by ceynri** [comment]
> 想问下扩展中 localStorage 存储的位置在哪里

不清楚为何要关心 localStorage 的存储，它由浏览器提供并管理，是相对比较安全的，除非你的浏览器正在被其他人所使用。

有两种方法可以获取到localStorage中存储的密码信息：

1. 点击扩展图标呼出窗口后，在窗口右键-检查-控制台，输入 `localStorage.getItem('cid')` 或 `localStorage.getItem('password')` 分别可以获取账号和密码信息
2. 同样是右键-检查，在选项卡中找到“应用程序”，侧边栏选取存储-本地存储，选择对应的chome-extentsion://xxx

---

> 能否增加清除账号或退出账号功能

这是一个好主意，但该扩展设计得比较简单，保证可用的前提下只提供最基础的功能。如果可以的话，可以说一下在什么场景下会需要使用到该功能？

**Comment by miRemid** [comment]
谢谢你的解答，由于我没有尝试过编写扩展程序，所以好奇扩展的localStorage的位置在哪里，没想到能够打开扩展的控制台

另外，关于清除或退出账号这种功能只是当时临时起意，后面仔细想想觉得没有什么必要

最后再次感谢你的解答
