### ISSUE TITLE
BRAS割接升级后登录网址无效了

### ISSUE THREAD

**Issue by Wenbobobo** [ceynri/szu-network-connecter#8]
校园网12.31进行BRAS割接升级，宽带的登录网址打不开了，插件也用不了了

**Comment by Wenbobobo** [comment]
http://172.30.255.42/

**Comment by Wenbobobo** [comment]
http://172.30.255.42/a79.htm
http://172.30.255.42/
更新了网页的登录网址，可是我不会pull request...

**Comment by chimaoshu** [comment]
看了一下，目前宿舍区的登录网址改为http://172.30.255.42:801/
登录的协议也改了，以前是POST，现在是GET，且多了很多字段，所以login-post.js需要做一些修改，已经修改好了。

**Comment by CaesarYP** [comment]
2021.12.31校园网大更新，原本我是登录界面抓包获得post的sh文件，但是现在是抓取get稍作修改才能用：
（个人信息已用中文隐去）
`auto_login.sh`
```
curl 'http://172.30.255.42:801/eportal/portal/login?callback=dr1003&login_method=1&user_account=%2C0%2C卡号&user_password=密码&wlan_user_ip=&wlan_user_ipv6=&wlan_user_mac=000000000000&wlan_ac_ip=&wlan_ac_name=&jsVersion=4.1.3&terminal_type=1&lang=zh-cn&v=5159&lang=zh' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37' \
  -H 'Accept: */*' \
  -H 'Referer: http://172.30.255.42/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' 
```
视频演示
【深圳大学drcom 路由器登录测试-哔哩哔哩】 https://b23.tv/IA6utFw

**Comment by CaesarYP** [comment]
不过我真的没学过这些，上面这些是参考某个教程搞会的，拿来给我的路由器用，仅供参考

**Comment by ceynri** [comment]
感谢反馈
请问非宿舍区的网络请求有变动么？

**Comment by chimaoshu** [comment]
> 感谢反馈 请问非宿舍区的网络请求有变动么？

目前没有

**Comment by CaesarYP** [comment]
> 2021.12.31校园网大更新，原本我是登录界面抓包获得post的sh文件，但是现在要改动才能用： 以下：BEFORE指2021.12.31前登录的post（去掉后两行） NOW指本人改动后可在2021.12.31后使用的post GET login指如今登陆界面能获取的一个login什么什么玩意的get，经我跟BEFORE的post一拼凑就能用了？ （个人信息已用中文隐去）
> 
> ```
> BEFORE:
> curl 'http://172.30.255.2/0.htm' \
>   -H 'Connection: keep-alive' \
>   -H 'Cache-Control: max-age=0' \
>   -H 'Upgrade-Insecure-Requests: 1' \
>   -H 'Origin: http://172.30.255.2' \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37' \
>   -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
>   -H 'Referer: http://172.30.255.2/0.htm' \
>   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
>   --data-raw 'DDDDD=卡号&upass=密码&0MKKey=%B5%C7%A1%A1%C2%BC&v6ip=' \
> 
> NOW:
> curl 'http://172.30.255.42:801/eportal/portal/login?callback=dr1003&login_method=1&user_account=%2C0%2C卡号&user_password=密码&wlan_user_ip=172.30.41.132&wlan_user_ipv6=&wlan_user_mac=000000000000&wlan_ac_ip=&wlan_ac_name=&jsVersion=4.1.3&terminal_type=1&lang=zh-cn&v=3623&lang=zh' \
>   -H 'Connection: keep-alive' \
>   -H 'Cache-Control: max-age=0' \
>   -H 'Upgrade-Insecure-Requests: 1' \
>   -H 'Origin: http://172.30.255.42' \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37' \
>   -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
>   -H 'Referer: http://172.30.255.42/' \
>   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
>   --data-raw 'DDDDD=卡号&upass=密码&0MKKey=%B5%C7%A1%A1%C2%BC&v6ip=' 
> 
> GET login:
> curl 'http://172.30.255.42:801/eportal/portal/login?callback=dr1003&login_method=1&user_account=%2C0%2C卡号&user_password=密码&wlan_user_ip=172.30.41.132&wlan_user_ipv6=&wlan_user_mac=000000000000&wlan_ac_ip=&wlan_ac_name=&jsVersion=4.1.3&terminal_type=1&lang=zh-cn&v=9877&lang=zh' \
>   -H 'Connection: keep-alive' \
>   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37' \
>   -H 'Accept: */*' \
>   -H 'Referer: http://172.30.255.42/' \
>   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
>   --compressed \
>   --insecure
> ```

视频演示
【深圳大学drcom 路由器登录测试-哔哩哔哩】 https://b23.tv/IA6utFw

**Comment by CaesarYP** [comment]
今天早上起来sh又没用了……显示ac认证失败

**Comment by CaesarYP** [comment]
> 今天早上起来sh又没用了……显示ac认证失败

重新抓包，发现抓得的get可以直接用，这波属实是自己不知道自己在干嘛了😅

**Comment by CaesarYP** [comment]
> > 今天早上起来sh又没用了……显示ac认证失败
> 
> 重新抓包，发现抓得的get可以直接用，这波属实是自己不知道自己在干嘛了😅

![image](https://user-images.githubusercontent.com/90097973/147842927-3ac6686a-82d0-4b99-aed1-888748da412b.png)
新发现，我今天按网上教程弄了一小时都没成功获取路由器在学校的内网ip（因为每天都会变脚本不改用不了），结果tmd把图中选中部分直接删掉就行了，明天再看看行不行😅😅😅

**Comment by ceynri** [comment]
发布商店遇到了点问题。。待修复后同步到该issue中
可以先在release中下载beta版本，本地加载插件，试试有没有问题
https://github.com/ceynri/szu-network-connecter/releases/tag/v1.4.0-beta

**Comment by chimaoshu** [comment]
> 发布商店遇到了点问题。。待修复后同步到该issue中 可以先在release中下载beta版本，本地加载插件，试试有没有问题 https://github.com/ceynri/szu-network-connecter/releases/tag/v1.4.0-beta

@ceynri 
60c6a1cbf9523bb94af2a6c036883e572425584d
这次commit以后，登录成功后会显示登录失败，看了下，问题在于：扩展会对3个登录地址都做请求，而访问宿舍区的旧登录地址的时候会被302重定向到新的登录页面，这次commit修改后的代码正好把这种情况漏掉了，所以代码执行到最下面返回一个失败的resolve，返回的“登录失败”被外层的Promise.race最先处理，所以扩展会显示“登录失败”。

解决：
红色框部分应该包在 isInfoResult 里面，因为302跳转后的内容 isInfoResult=false
![image](https://user-images.githubusercontent.com/56833537/147848418-890c38d5-5640-4a35-b512-d0fe260eb8c3.png)
或者直接删掉旧的登录地址，反正也没用了，访问它只会一直重定向

**Comment by yepHiu** [comment]
根据CaesarYP 给我发送的新版本可以正常使用!
![image](https://user-images.githubusercontent.com/93661415/147864176-aaa0839d-f662-4f7d-8c2d-eaca68078e5c.png)

**Comment by ceynri** [comment]
Chrome商店[已更新](https://chrome.google.com/webstore/detail/%E6%A0%A1%E5%9B%AD%E7%BD%91%E4%B8%80%E9%94%AE%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81/mmeaolnimopgipjfbgobdlgkojojonop)，有需要的可以更新至1.4.x。
但是手动下载crx安装的方式在新版Chrome/Edge里貌似已经被禁止了。。目前想到的兜底方案是直接下载源码并以开发者模式加载
这边尝试上传一下Edge商店，以方便不便科学上网且使用Edge浏览器的用户

**Comment by ceynri** [comment]
>  ...但是手动下载crx安装的方式在新版Chrome/Edge里貌似已经被禁止了...

@CaesarYP @yepHiu 关于 1.4.0 版本 crx 文件无法安装的问题，刚刚想起来是需要开发者从商店后台下载 crx 文件，而不能自己本地打包，否则签名不一致会无法通过 chrome 的检查。

现已更新 [Release 1.4.1](https://github.com/ceynri/szu-network-connecter/releases) 的 crx 和 xpi 文件可供下载，不用再使用开发模式加载本地代码了
